##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################

obj-m := k3g.o

clean:
	rm -f *.o *.ko *.mod.* *~ .*.cmd Module.symvers modules.order

