# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_INPUT_ZEUS_EAR_KEY)	+= zeus_earkey.o
# OMS Accessory class
obj-$(CONFIG_SEC_HEADSET_CLASS_FOR_OMS)	+=	accessory.o
# SIO Switch Driver
obj-$(CONFIG_SWITCH_SIO)	+= switch_sio.o
