
ifdef CONFIG_MACH_OMAP_SAMSUNG
EXTRA_CFLAGS += -I$(srctree)/samsung/rfs_fsr/drivers
EXTRA_CFLAGS += -I$(srctree)/samsung/rfs_fsr/include
endif

MOD_NAME = storage
obj-$(CONFIG_PHONE_STORAGE) += $(MOD_NAME).o

