/**
 * Copyright (C) 2010, Samsung Electronics, Co., Ltd. All Rights Reserved.
 *  Written by System S/W Group, Open OS S/W R&D Team,
 *  Mobile Communication Division.
 */

/**
 * Project Name : OMAP-Samsung Linux Kernel for Android
 *
 * Project Description :
 *
 * Comments : tabstop = 8, shiftwidth = 8, noexpandtab
 */

/**
 * File Name : mux_p1lite_rev_r03.h
 *
 * File Description :
 *
 * Author : System Platform 2
 * Dept : System S/W Group (Open OS S/W R&D Team)
 * Created : 25/Nov/2010
 * Version : Baby-Raccoon
 */

#ifndef __MUX_P1LITE_H__
#define __MUX_P1LITE_H__

#define OMAP_GPIO_LCD_LDO_EN	3
#define OMAP_GPIO_USB_SEL_2		10
#define OMAP_GPIO_FUEL_INT_N		12
#define OMAP_GPIO_NAND_INT		13
#define OMAP_GPIO_ACCESSORY_INT		14
#define OMAP_GPIO_DOCK_INT		15
#define OMAP_GPIO_CHG_ING_N		16
#define OMAP_GPIO_SIM_DETECT		21
#define OMAP_GPIO_SYS_DRM_MSECURE	22
#define OMAP_GPIO_T_FLASH_DETECT	23
#define OMAP_GPIO_KEY_PWRON		24
#define OMAP_GPIO_PS_HOLD_PU		25
#define OMAP_GPIO_FLM_SEL		26
#define OMAP_GPIO_CON_CP_SEL		27
#define OMAP_GPIO_ALS_NRST		28
#define OMAP_GPIO_VOLUME_DOWN		29
#define OMAP_GPIO_GPS_EN		35
#define OMAP_GPIO_GPS_CNTL		36
#define OMAP_GPIO_SENSOR_I2C_SCL	37
#define OMAP_GPIO_SENSOR_I2C_SDA	38
#define OMAP_GPIO_GPS_NRST		39
#define OMAP_GPIO_MICBIAS_EN		40
#define OMAP_GPIO_FUEL_SDA		41
#define OMAP_GPIO_LCD_EN_SET		42
#define OMAP_GPIO_CP_RST		43
#define OMAP_GPIO_PCM_SEL		52
#define OMAP_GPIO_EAR_AMP_SHDN		53
#define OMAP_GPIO_JIG_ON18		54
#define OMAP_GPIO_FUEL_SCL		55
#define OMAP_GPIO_VIBTONE_FREQ		56
#define OMAP_GPIO_USB_SEL_1         57
#define OMAP_GPIO_ACCESSORY_EN	58
#define OMAP_GPIO_SPK_LINE_OUT		60
#define OMAP_GPIO_EAR_ADC_3_5		61
#define OMAP_GPIO_KEY_LED_EN		62
#define OMAP_GPIO_BT_NRST			63
#define OMAP_GPIO_CAM_CIF_NRST		64
#define OMAP_GPIO_LVDS_SHDN			65
#define OMAP_GPIO_5M_CAM_NRST		98
#define OMAP_GPIO_WLAN_HOST_WAKE	99
#define OMAP_GPIO_VOLUME_UP		100
#define OMAP_GPIO_CAM_CIF_NSTBY		101
#define OMAP_GPIO_EAR_MICBIAS_EN	102
#define OMAP_GPIO_PDA_ACTIVE		111
#define OMAP_GPIO_DET_3_5		112
#define OMAP_GPIO_EAR_SEND_END		113
#define OMAP_GPIO_ACC_INT2		114
#define OMAP_GPIO_ACC_INT1		115
#define OMAP_GPIO_UART_SEL		126
#define OMAP_GPIO_HW_REV1		127
#define OMAP_GPIO_RESET_REQ_N		140
#define OMAP_GPIO_VIBTONE_EN		141
#define OMAP_GPIO_TOUCH_INT		142
#define OMAP_GPIO_TOUCH_EN		143
#define OMAP_GPIO_CAM_EN1		152
#define OMAP_GPIO_CAM_5M_NSTBY		153
#define OMAP_GPIO_PHONE_ACTIVE		154
#define OMAP_GPIO_AMP_SHDN		155
#define OMAP_GPIO_FLASH_EN1			156
#define OMAP_GPIO_CHG_EN		157
#define OMAP_GPIO_FLASH_EN2			158
#define OMAP_GPIO_MASSMEMORY_EN		159
#define OMAP_GPIO_WLAN_EN		160
#define OMAP_GPIO_CMC_SCL			161
#define OMAP_GPIO_CMC_SDA			162
#define OMAP_GPIO_CP_INT		163
#define OMAP_GPIO_MSENSE_NRST		164
#define OMAP_GPIO_MOVI_RST		167
#define OMAP_GPIO_AP_I2C_SCL		168
#define OMAP_GPIO_LVDS_EN		170
#define OMAP_GPIO_CMC_SHDN		171
#define OMAP_GPIO_CMC_SLEEP		172
#define OMAP_GPIO_CMC_BYPASS	173
#define OMAP_GPIO_CMC_RST		174
#define OMAP_GPIO_CMC_EN		177
#define OMAP_GPIO_IPC_SRDY		181
#define OMAP_GPIO_IPC_MRDY		182
#define OMAP_GPIO_AP_I2C_SDA		183
#define OMAP_GPIO_CAM_EN2		186
#define OMAP_GPIO_LCD_ID2		0
#define OMAP_GPIO_PS_VOUT		0
#define OMAP_GPIO_CP_VBUS_EN		0
#define OMAP_GPIO_FM_nRST		0
#define OMAP_GPIO_LEVEL_SDA		127
#define OMAP_GPIO_LEVEL_SCL		129
#endif /* __MUX_P1LITE_H__ */


#if 0
/*
 * arch/arm/plat-omap/include/mach/mux_latona.h
 *
 */

#ifndef _MUX_LATONA_H_
#define _MUX_LATONA_H_

#define OMAP_GPIO_JACK_NINT		10
#define OMAP_GPIO_FUEL_INT_N		12
#define OMAP_GPIO_NAND_INT		13
#define OMAP_GPIO_FM_SCL		14
#define OMAP_GPIO_FM_SDA		15
#define OMAP_GPIO_CHG_ING_N		16
#define OMAP_GPIO_EARPATH_SEL		21
#define OMAP_GPIO_SYS_DRM_MSECURE	22
#define OMAP_GPIO_T_FLASH_DETECT	23
#define OMAP_GPIO_KEY_PWRON		24
#define OMAP_GPIO_PS_HOLD_PU		25
#define OMAP_GPIO_HW_REV2		26
#define OMAP_GPIO_CON_CP_SEL		27
#define OMAP_GPIO_ALS_EN		28
#define OMAP_GPIO_TA_NCONNECTED		29
#define OMAP_GPIO_GPS_EN		35
#define OMAP_GPIO_GPS_CNTL		36
#define OMAP_GPIO_SENSOR_SCL		37
#define OMAP_GPIO_SENSOR_SDA		38
#define OMAP_GPIO_GPS_NRST		39
#define OMAP_GPIO_FM_INT		40
#define OMAP_GPIO_FUEL_SDA		41
#define OMAP_GPIO_LCD_LDO_EN		42
#define OMAP_GPIO_CP_RST		43
#define OMAP_GPIO_PCM_SEL		52
#define OMAP_GPIO_PS_VOUT		53
#define OMAP_GPIO_JIG_ON18		54
#define OMAP_GPIO_FUEL_SCL		55
#define OMAP_GPIO_VIBTONE_FREQ		56
#define OMAP_GPIO_EN_TEMP_VDD		58
#define OMAP_GPIO_LCD_ID2		61
#define OMAP_GPIO_LCD_ID1		62
#define OMAP_GPIO_BT_NRST		63
#define OMAP_GPIO_CAM_CIF_NRST		64
#define OMAP_GPIO_KEY_HOME		0 // 65
#define OMAP_GPIO_LVDS_SHDN		65
#define OMAP_GPIO_5M_CAM_NRST		98
#define OMAP_GPIO_WLAN_HOST_WAKE	99
#define OMAP_GPIO_CAM_CIF_NSTBY		101
#define OMAP_GPIO_EAR_MICBIAS_EN	102
#define OMAP_GPIO_PDA_ACTIVE		111
#define OMAP_GPIO_DET_3_5		112
#define OMAP_GPIO_EAR_SEND_END		113
#define OMAP_GPIO_ACC_INT2		114
#define OMAP_GPIO_ACC_INT1		115
#define OMAP_GPIO_UART_SEL		126
#define OMAP_GPIO_HW_REV1		127
#define OMAP_GPIO_HW_CP_INT		128
#define OMAP_GPIO_RESET_REQ_N		140
#define OMAP_GPIO_VIBTONE_EN		141
#define OMAP_GPIO_TOUCH_INT		142
#define OMAP_GPIO_TOUCH_EN		143
#define OMAP_GPIO_CAM_EN1		152
#define OMAP_GPIO_CAM_5M_NSTBY		153
#define OMAP_GPIO_PHONE_ACTIVE		154
#define OMAP_GPIO_AMP_SHDN		155
#define OMAP_GPIO_FM_nRST		156
#define OMAP_GPIO_CHG_EN		157
#define OMAP_GPIO_LED_EN1		158
#define OMAP_GPIO_MASSMEMORY_EN		159
#define OMAP_GPIO_WLAN_EN		160
#define OMAP_GPIO_CP_VBUS_EN		0 // 161
#define OMAP_GPIO_LED_EN2		0 // 162
#define OMAP_GPIO_CMC_SCL		161
#define OMAP_GPIO_CMC_SDA		162
#define OMAP_GPIO_HW_REV0		163
#define OMAP_GPIO_MSENSE_NRST		164
#define OMAP_GPIO_MOVI_RST		167
#define OMAP_GPIO_AP_I2C_SCL		168
#define OMAP_GPIO_MLCD_RST		0 // 170
#define OMAP_GPIO_CAM_EN3		0 // 177
#define OMAP_GPIO_LVDS_EN		170
#define OMAP_GPIO_CMC_SHDN		171
#define OMAP_GPIO_CMC_SLEEP		172
#define OMAP_GPIO_CMC_BYPASS		173
#define OMAP_GPIO_CMC_RST		174
#define OMAP_GPIO_CMC_EN		177
#define OMAP_GPIO_IPC_SRDY		181
#define OMAP_GPIO_IPC_MRDY		182
#define OMAP_GPIO_AP_I2C_SDA		183
#define OMAP_GPIO_CAM_EN2		186

#endif /* _MUX_LATONA_H_ */
#endif
