##
# Copyright (C) 2010, Samsung Electronics Co., Ltd. All Rights Reserved.
#  Written by System S/W Group, Open OS S/W R&D Team,
#  Mobile Communication Division.
##

##
# Project Name : Samsung Private Third-Party Device Drivers
#
# Project Description :
#
# Comments : tabstop = 8, shiftwidth = 8, noexpandtab
##

##
# File Name : Makefile
#
# File Description :
#
# Author : Joo, Young Jin (#4349, youngjin79.joo@samsung.com)
# Dept : System S/W Group (Open OS S/W R&D Team)
# Created Date : 09-Jul-2010
# Version : Baby-Raccoon
##

#obj-$(CONFIG_RFS_FSR)		+= rfs_fsr/drivers/fsr/
obj-$(CONFIG_TINY_FSR)		+= rfs_fsr/drivers/tfsr/
#obj-$(CONFIG_RFS_FS)		+= rfs_fsr/fs/rfs/
obj-$(CONFIG_SAMSUNG_BATTERY)	+= battery/
obj-$(CONFIG_FMRADIO)	+= fm_si4709/
obj-$(CONFIG_SAMSUNG_VIBETONZ)	+= vibetonz/
#obj-$(CONFIG_SAMSUNG_J4FS)	+= j4fs/
obj-$(CONFIG_SAMSUNG_PARAM)	+= param/
obj-$(CONFIG_INPUT_YAS529)	+= yas529/
obj-$(CONFIG_INPUT_BMA222)	+= bma222/
obj-$(CONFIG_INPUT_GP2A)	+= gp2a/
obj-$(CONFIG_INPUT_ORIENTATION) += orientation/
obj-$(CONFIG_SUPPORT_GPS)	+= gps/
obj-$(CONFIG_INPUT_BH1721)	+= bh1721/
obj-$(CONFIG_INPUT_K3G)     += k3g/
obj-$(CONFIG_INPUT_BMA023)  += bma023/

