#!/sbin/ext/busybox sh

usage="usage: propset <key> <value>"

if ! [ -d /data/prop ]; then
  /sbin/ext/busybox mkdir -p /data/prop
fi
 
if ! [ -d /data/prop/$1 ]; then
  if ! [ "$2" = "" ]; then
    echo -n $2 > /data/prop/$1
  else
    echo $usage
  fi
else
  echo $usage
fi
