#!/sbin/ext/busybox sh

if ! [ -d /data/prop ]; then
  /sbin/ext/busybox mkdir -p /data/prop
fi

if [ "$1" = "" ]; then
  for i in $(ls /data/prop/*)
  do 
    echo "[`echo $i | cut -d "/" -f4`]: [`cat $i`]"
  done
else
  if [ -f /data/prop/$1 ]; then
    echo `cat /data/prop/$1`
  else
    echo ""
  fi
fi;
