##
# Copyright (C) 2010-2011, Samsung Electronics Co., Ltd. All Rights Reserved.
#  Written by System S/W Group, Open OS S/W R&D Team,
#  Mobile Communication Division.
##

##
# Project Name : Samsung Debug-Level Control Driver
#
# Project Description :
#
# Comments : tabstop = 8, shiftwidth = 8, noexpandtab
##

##
# File Name : Makefile
#
# File Description :
#
# Author : System Platform 2
# Dept : System S/W Group (Open OS S/W R&D Team)
# Renewal : 27/Jan/2011
# Version : Baby-Raccoon
##

obj-$(CONFIG_SAMSUNG_DBG_LEVEL) += level.o
