#
# Makefile for the kernel multimedia device drivers.
#

obj-y        := dvb-core/	\
		frontends/	\
		ttpci/		\
		ttusb-budget/	\
		b2c2/		\
		bt8xx/		\
		dvb-usb/	\
		pluto2/		\
		dm1105/		\
		pt1/

#		ttusb-dec/
#		siano/
#		ngene/
#		mantis/


obj-$(CONFIG_DVB_FIREDTV)	+= firewire/
